### ISSUE TITLE
unable to add header and footer on PDF

### ISSUE THREAD

**Issue by cisdev213** [pdfshift/pdfshift-node#2]
I am using PDFShift for my project. its working fine but i need to add custom header and footer on my PDF and when i add it its give me error 

>   body: { code: 400, errors: { footer: [Object] }, success: false } }
> errors :  { footer: { '0': 'Rogue field' } }

Please let me know how i add it. below is my code. 

>  pdfshift.prepare('https://localhost/viewpdf') 
>     .footer({source: "test data", spacing: '50px'})
>     .convert()
>     .then(function (binary_file) {
>       let todayDate = new Date;
>       let pdfName = todayDate.getTime();
>       fs.writeFile('//pdf/'+pdfName+'.pdf', binary_file, "binary", function () {return ReS(res, {})
>     })
>     .catch(function({message, code, response, errors = null}) {
>     //     console.log(message) ;
>     // console.log("code : ",code) ;
>     // console.log("response : ",response) ;
>     // console.log("errors : ",errors) ;
>       return ReE(res, " PDF is not created." );
>     })

**Comment by cnicodeme** [comment]
Hi,

I recommend you to reach out to support in the futur for help, we reply faster.

Try this instead:

`.footer("test data", '50px')`

And let me know :)

**Comment by cisdev213** [comment]
> pdfshift.prepare('https://www.google.com')
>     .footer("test data", '50px')
>     .convert()
>     .then(function (binary_file) {
>         fs.writeFile('result.pdf', binary_file, "binary", function () {return ReS(res, { pdf: " pdf generated" });})
>     })
>     .catch(function({message, code, response, errors = null}) {return ReE(res, " PDF is not created." );})

Still not working.

**Comment by cnicodeme** [comment]
Hi

Here's a working example:

```
pdfshift.prepare('https://example.com')
    .footer({source: '<div style="font-size: 12px">Page {{page}} of {{total}}</div>', spacing: '50px'})
    .convert()
    .then(function (binary_file) {
         // Manage the binary file
    })
    .catch(function({message, code, response, errors = null}) {
        console.warn('ERROR!')
        console.log(arguments)
    });
```

Sorry about the late response ...
