### ISSUE TITLE
2.0.1 Breaking Changes

### ISSUE THREAD

**Issue by tylergets** [pdfshift/pdfshift-node#5]
Hello, we are a customer of Pdfshift and realized 2.0.1 has broken our code. We have reverted to 2.0.0 for now but want to make this issue aware.

It appears convert is now returning a stream instead of the buffer we were expecting.

**Comment by cnicodeme** [comment]
Yes indeed.

The v2.0.1 now return a Buffer instead of the raw data (following some issues in certain cases).

In order to get the raw data, you can call `.toString()` on the response from the PDFShift client.

**Comment by tylergets** [comment]
This does not work with our app, calling .toString() returns "[Object]" 

We are receiving a PassThrough stream

**Comment by cnicodeme** [comment]
Did you use the latest version? Because it returns a Buffer (which then works with `toString` whereas the 2.0.0 returns the PassThrough stream that requires a bit more work).
